name: Backup to Amazon S3

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: mongodb-awesome-backup  # set this to your Amazon ECR repository name

defaults:
  run:
    shell: bash

jobs:
  backup-to-s3:
    name: Backup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: public.ecr.aws/d4w2c1x5/mongodb-awesome-backup:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate backup
        id: build-image
        runs-on: public.ecr.aws/d4w2c1x5/mongodb-awesome-backup:latest
        run: |
          ls
          pwd
          ls -a
          docker run --rm \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e TARGET_BUCKET_URL="s3://aiid-backups-public" \
            -e BACKUPFILE_PREFIX="backup" \
            -e MONGODB_URI="mongodb+srv://EScmnlEQHM1pWwWM@aiiddev-aqdmh.gcp.mongodb.net" \
            -e MONGODB_HOST="mongo" \
            -e MONGODB_DBNAME="AIIDDev" \
            -e MONGODB_USERNAME="readonlyuser" \
            -e MONGODB_PASSWORD="EScmnlEQHM1pWwWM" \
            -e MONGODB_AUTHDB="admin" \
            -e AWSCLI_ENDPOINT_OPT="s3://aiid-backups-public" \
            -v ~:/mab \
            public.ecr.aws/d4w2c1x5/mongodb-awesome-backup:latest
