name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      # Environments to connect to GCS.
      DOT_BOTO_OAUTH: ${{ secrets.DOT_BOTO_OAUTH }}
      GCP_ACCESS_KEY_ID: ${{ secrets.GCP_ACCESS_KEY_ID }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SECRET_ACCESS_KEY: ${{ secrets.GCP_SECRET_ACCESS_KEY }}
      TARGET_BUCKET_URL_PREFIX: gs://staging.mongodb-awesome-backup.appspot.com/test
      # Match with the time zone of the mongodb-awesome-backup container.
      TZ: Asia/Tokyo
      # Slack notification
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOTIFY_MESSAGE: '${{ github.repository }} (${{ github.workflow }}): `${{ github.ref }}`@${{ github.actor }}'
      # docker-compose version (it need over version 1.25.0 to using BuildKit. see: https://github.com/docker/compose/releases/tag/1.25.0)
      DOCKER_COMPOSE_VERSION: 1.25.3

    steps:
    - uses: actions/checkout@v2
    
    - name: Set service account key path
      run: |
        echo ::set-env name=GCP_SERVICE_ACCOUNT_KEY_JSON_PATH::"$(pwd)/tmp/key.json"

    - name: Install Docker Compose
      run: |
        DOCKER_COMPOSE_PATH="~/bin/docker-compose"
        mkdir -p $(dirname ${DOCKER_COMPOSE_PATH})

        # ref: https://github.com/docker/compose/releases
        curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > ${DOCKER_COMPOSE_PATH}
        chmod +x ${DOCKER_COMPOSE_PATH}
        echo PATH ${PATH}
        echo "::add-path::${DOCKER_COMPOSE_PATH}"

    - name: Run integration tests
      run: |
        # Create a temporary service account key file
        mkdir -p $(dirname ${GCP_SERVICE_ACCOUNT_KEY_JSON_PATH})
        echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > ${GCP_SERVICE_ACCOUNT_KEY_JSON_PATH}

        # Set environment for integration tests
        BUCKET_NAME_PREFIX=`echo $GITHUB_REPOSITORY | tr '/' '_'`
        export TARGET_BUCKET_URL="${TARGET_BUCKET_URL_PREFIX}/${BUCKET_NAME_PREFIX}_${GITHUB_RUN_ID}/"

        export DOCKER_BUILDKIT=1
        export COMPOSE_DOCKER_CLI_BUILD=1
        docker-compose -v
        which docker-compose
        echo PATH ${PATH}
        test/all.sh

    - name: Remove the temporary service account key file
      run: |
        rm -f ${GCP_SERVICE_ACCOUNT_KEY_JSON_PATH}

    - name: Slack Notification
      if: always()
      uses: innocarpe/actions-slack@v1
      with:
        status: ${{ job.status }} # Required
        success_text: '*Success* ${{ env.NOTIFY_MESSAGE }}'
        failure_text: '*Fail* ${{ env.NOTIFY_MESSAGE }}'
        cancelled_text: '*Cancelled* ${{ env.NOTIFY_MESSAGE }}'
